### ISSUE TITLE
can it exclude input and text areas ?

### ISSUE THREAD

**Issue by vijaythecoder** [iFgR/vue-shortkey#1]
it might usually not good approach to set `c` as a short key but I had to do it for my purpose. so when I use input text/text area and type c , it fires up the short cut key. If there is a way to exclude the input and text areas that would be great

**Comment by iFgR** [comment]
Thanks to your issue!
Do you really need to use **C** as shortcut? The **Alt+C** wouldn't did what you need?
By the way, as you pointed, I think that will be great if we have a modifier to avoid short key.

What do you think? As:
 ```
v-shortkey.void
```
To avoids any short key in the element.
Would that solve your need?

**Comment by iFgR** [comment]
I've created two ways to avoid shortcuts.
**Strict method**
You can add ``` _v-shortkey.void_ ``` within the element you want to prevent from running shortcut

**Global method**
You can add the _prevent_ option in the ``` _Vue.use()_ ``` global method.

```javascript
Vue.use ( 'vue-shortkey', {prevent: [ 'input', 'textarea']})
```
I think the latter solution solves your problem.

Give me feedback if it works or not.

**Comment by javierojeda94** [comment]
Is there any way to use some selectors on this topic? i.e. 
```html
<input type="text" class="form-control not-shortkey">
```
I want to use
```js
Vue.use('vue-shortkey', { prevent: ['.not-shortkey'] } ) 
```
Or maybe
```js
Vue.use('vue-shortkey', { prevent: ['input.not-shortkey'] } ) 
```

I can open a new issue for this

**Comment by iFgR** [comment]
I will update the code in this weekend to support it.
Open a new issue please!

**Comment by iFgR** [comment]
Code updated. Could you test?

**Comment by javierojeda94** [comment]
I'm on my way to test it right now!
