### ISSUE TITLE
Undefined property el in unbind hook

### ISSUE THREAD

**Issue by Hiws** [iFgR/vue-shortkey#102]
Whenever i change page/route in my application, these errors are thrown for each `v-shortkey` present on that page/route.

![Image of error](https://i.imgur.com/yEn0wxk.png)

The shortkeys still work as they should, however having my console spammed by 100's of error messages is making things hard to debug at times.

I couldn't find an other reports of this issue, so I'm not sure if it's on my end or not.

I'm using version `3.1.7`

**Comment by iFgR** [comment]
Your code is on public repo or any place that I can check?
