### ISSUE TITLE
"ctrl + s" for windows and "cmd + s" for mac

### ISSUE THREAD

**Issue by ssmali1505** [iFgR/vue-shortkey#103]
I have the following questions :
1. What is the shortcut key format for cmd + s? 
2. Based on running OS how we can use this shortcut keys ctrl vs cmd?

**Comment by iFgR** [comment]
1. meta is the key for Super on Window and Cmd on Mac
`<my-component v-shortkey="['meta', ' 's']" @shortkey.propagate="anAction()"></my-component>`

2. You can use the [Multi Key](https://github.com/iFgR/vue-shortkey#multi-keys) to allow more than one combination to the same action
`<button v-shortkey="{windows: ['ctrl', 's'], mac: ['meta', 's']}" @shortkey="theAction">Save</button>`
