### ISSUE TITLE
Works incorrect when bind same shortkeys.

### ISSUE THREAD

**Issue by SamirGuo** [iFgR/vue-shortkey#106]
description: 
 It always fire the last element action when bind same short keys.

repo.
the action will always execute action2.

`
<template>
<el-form-item>
      <el-input v-shortkey="['alt', 'enter']" @shortkey.native="action1" />
      <el-input v-shortkey="['alt', 'enter']" @shortkey.native="action2" />
 </el-form-item>
</template>

<script lang="ts">
  export default {
    methods: {
      action1: function () {
        console.log('==== alt+ enter 1');
      },
      action2: function () {
        console.log('==== alt+ enter 2');
      },
    },
  }
</script>
`

**change the code line 119 like this will fix it.**
`
       // elm[elm.length - 1].dispatchEvent(e)
        elm.some(el => {
            if (el === target || el.contains(target)) {
                el.dispatchEvent(e);
                return true;
            }
        });
`

**Comment by iFgR** [comment]
You're dispatching 2 methods with the same key combination.
What if you dispatch to an action hub? like this:
```
<el-input v-shortkey="['alt', 'enter']" @shortkey.native="actionHub" />

<script>
  methods: {
    actionHub () {
      this.action1();
      this.action2();
    },
    action1 () {},
    action2 () {}
  }
}
```
