### ISSUE TITLE
Republish with NODE_ENV=production

### ISSUE THREAD

**Issue by francois2metz** [iFgR/vue-shortkey#11]
Hi,

I noticed that the build of vue-shortkey include the sourcemaps. These should not be there. Could you recompile the bundle with NODE_ENV=production and republish your package ?

Thanks !

**Comment by iFgR** [comment]
Hi!
Sorry, I don't understood.
There's no sourcemap in dist folder. If I run build with NODE_ENV=production , then there will be the sourcemap in the folder.

**Comment by francois2metz** [comment]
Sorry i was not clear.

The problem is the published package use the `eval-source-map` setting. When I use vue-shortkey in my app, the sourcemaps of vue-shortkey are embeded in the final bundle, and not outside as I want.

For some reason, webpack don't know how to extract the sourcemaps from the final build.

The fix would be to either to:
-  rebuild with NODE_ENV=production and push the sourcemaps as a separate file (so I can load it using the source-map-loader https://webpack.js.org/loaders/source-map-loader/)
- don't generate any sourcemaps and don't minimize the file

**Comment by iFgR** [comment]
Ok, so...
I did the the build again with the 'production' flag and it's create a sourcemap file inside the dist folder.
![screenshot from 2017-07-21 08-47-52](https://user-images.githubusercontent.com/8412591/28462366-5047e6c0-6df1-11e7-9091-173f5fd17919.png)

Would that help you?

**Comment by francois2metz** [comment]
Yes definitely!

**Comment by iFgR** [comment]
Ok, I will commit!

**Comment by francois2metz** [comment]
Thanks a lot! It's perfect.
