### ISSUE TITLE
Two number as short key is not working

### ISSUE THREAD

**Issue by lustan3216** [iFgR/vue-shortkey#111]
```
<i
  v-shortkey="['1', '2']"
  @shortkey="dosomething"
/>
```
This combination is not working, Is that possible to support that?

**Comment by iFgR** [comment]
Combined keys is only supported when using ctrl, alt, shift and meta key.
We are working on sequential key to support this.

**Comment by alexbeeston** [comment]
Has this been resolved yet? I need to be able to respond to two keys that aren't necessarily the ones listed above.
