### ISSUE TITLE
.avoid not working with v-color-picker

### ISSUE THREAD

**Issue by WhatWhatz** [iFgR/vue-shortkey#113]
the `v-shortkey.avoid` does not work on the vuetify `v-color-picker`. I believe that the text input is inside  `v-color-picker` and therefor the avoid does not work. Is there anyway to propagate the .avoid to all the children of an element?

**Comment by WhatWhatz** [comment]
I tried to use `Vue.use('vue-shortkey', { prevent: ['input', 'textarea'] })` but it still doesn't work. and It was an input element.

**Comment by medzhidov** [comment]
Anybody read this? I have the same problem!

**Comment by WhatWhatz** [comment]
Found a work around using `Vue.use(require('vue-shortkey'), { prevent: ['input', 'textarea'] })` in `main.js`.

**Comment by iFgR** [comment]
v-color-picker should encapsulate the input element and the avoid command isn't applied to them.
So try to apply the prevention to the class.

```
Vue.use('vue-shortkey', { prevent: ['.input-color-picker-style-class'] })
```
