### ISSUE TITLE
Table shortkey

### ISSUE THREAD

**Issue by SuperKiwi** [iFgR/vue-shortkey#12]
Hello @iFgR and 👏 👏 👏 for this package

Just wondering, would you recommend a way to use shortkey on a long table with inputs on each row ?
Something like `@shortkey="['ctrl', 'n']"` to focus on next input and `@shortkey="['ctrl', 'p']"` to focus on previous input ?

Thank you

**Comment by iFgR** [comment]
Hi, thanks so much!
If your app have a button up and down to move the focus on a list, attach the shortkey to it.
