### ISSUE TITLE
how to use on Router-Link?

### ISSUE THREAD

**Issue by jara77** [iFgR/vue-shortkey#129]
The plugin works great with BUTTON but i dont now how to make work with the ROUTER-LINK

Example:

![111](https://user-images.githubusercontent.com/60484149/112374121-f484d700-8c9e-11eb-86d5-a161437ba9aa.PNG)

![222](https://user-images.githubusercontent.com/60484149/112374153-fcdd1200-8c9e-11eb-8fde-eb7160021c2d.PNG)

**Comment by iFgR** [comment]
Router link is a abstract component that render another one.
Try to use @shortkey.native="downloadPdf()" or add the shortkey directive into the <i> element.
