### ISSUE TITLE
Multiple shortcuts per element?

### ISSUE THREAD

**Issue by timpulver** [iFgR/vue-shortkey#19]
Is it possible to have multiple shortcuts per elements somehow?

I need:

- `cmd + c` to copy
- `cmd + d` to duplicate

Having the attribute multiple times does not work:

```
 - duplicate attribute: v-shortkey
 - duplicate attribute: @shortkey
```

**Comment by iFgR** [comment]
Hi,thanks to your issue!
I have received many questions like this and I am working on a feature to bring these features to our plugin

**Comment by iFgR** [comment]
@francois2metz can you test the branch multi_keys? before we pull to master??
