### ISSUE TITLE
It doesn't work on component

### ISSUE THREAD

**Issue by sonmunehiro** [iFgR/vue-shortkey#22]
Hi, this plugin is good!!

But I found a problem.

It works:
`<div v-shortkey="['ctrl', 'p']" @shortkey="test"></div>`

It doesn't work:
`<my-component v-shortkey="['ctrl', 'p']" @shortkey="test"></my-component>`

Is there any way to solve the issue?

**Comment by francois2metz** [comment]
On a component, you should use `@shortkey.native` to listen. Otherwise, you are listening to events triggered by the component.

**Comment by francois2metz** [comment]
The doc will be updated in #23.

**Comment by sonmunehiro** [comment]
@francois2metz Thank you! It works
