### ISSUE TITLE
multi key

### ISSUE THREAD

**Issue by sonmunehiro** [iFgR/vue-shortkey#26]
Thank you for updating.
I updated to 3.0.0.
And add the code:
`<span v-shortkey="{win:['ctrl', 'd'],mac:['meta', 'd']}"  @shortkey="test"></span>`
But the console shows:
`Error in directive shortkey bind hook: "TypeError: n.join is not a function"`
Is there anything I need to do?
Thank you

**Comment by sonmunehiro** [comment]
Maybe because `dist/index.js` is not updated?

**Comment by francois2metz** [comment]
Hi @sonmunehiro, thanks for reporting. I have fixed the issue and published the version 3.0.1.
