### ISSUE TITLE
How to bind '?'

### ISSUE THREAD

**Issue by nkostadinov** [iFgR/vue-shortkey#29]
I'm having trouble binding "?". I tried ['?'] and ['shift', '/'] with no luck. How can I bind to this combination ? 

Also is it possible to bind two key combinations to one srcKey e.g. I want to have 'help' invoked by 'h' or by '?'

**Comment by iFgR** [comment]
Right, I will check this out.
We don't have mapped some symbols and '?' probably is one of them

**Comment by iFgR** [comment]
Use ['shift', '?']
