### ISSUE TITLE
Key sequences (Konami code)

### ISSUE THREAD

**Issue by jonathan82** [iFgR/vue-shortkey#30]
Does this plugin support a sequence of keys to activate a shortcut?  for example if I hit "up up down down" in order can this be detected as a single hotkey?

**Comment by francois2metz** [comment]
Hi @jonathan82. Nope this plugin doesn't support this kind of sequence.

**Comment by ben-turner** [comment]
Are there plans to support this? My use case is that I want to use a prefix to modify the shortcut. Eg, `ga` will go to the page called "actions", but just `a` adds something on the current page.
