### ISSUE TITLE
Span over multiple components

### ISSUE THREAD

**Issue by lucas-bremond** [iFgR/vue-shortkey#34]
Hi!

Is there a way to use the `keypress` event over multiple elements at the same time?

For example, I have a list of components created using `v-for` (i.e., the various instances use the same base component) and I would like to perform some action over all of them when pressing `shift`.

Thank you!

**Comment by iFgR** [comment]
Hi!
To map SHIFT key to do an action inside more than one component, prefer to use the **Vuex**.

See the schema below:

![shortkey-vuex](https://user-images.githubusercontent.com/8412591/34916622-5d0cb5cc-f922-11e7-902a-e504cc3c84f4.png)

I would have the main component with only one **shortkey** calling a **Vuex Mutation**.
It would encapsulate all the components which will be rendered by the v-for and inside each component, we would have a **Vuex Getter** to know when **SHIFT** was pressed.

**Comment by iFgR** [comment]
if you don't want to use Vuex, you can call a function to change one boolean data model on cmp-container and create a prop inside the listed component passing these data model
