### ISSUE TITLE
Is it possible to add / or ? to the key mapping?

### ISSUE THREAD

**Issue by darkzerone** [iFgR/vue-shortkey#39]
I would like to  use / or ? in my application with shortcuts is it possible to add them?

**Comment by iFgR** [comment]
Hi,
The **?** key is used with **SHIFT** key in almost keyboard that I've seen, so, use "['**shift**', '**?**']" to handle the **?** key.

I'll test the **/** key and tell you how to use it...

**Comment by francois2metz** [comment]
I tried `/`. It works at least on qwerty keyboards.
