### ISSUE TITLE
Shortkey fires only on last instance of component

### ISSUE THREAD

**Issue by Brendonald** [iFgR/vue-shortkey#41]
If I have the following template:
```
<template>
    <div class="template-root">
        <my-comp v-shortkey.native="['meta', 'enter']" @shortkey="() => console.log('1')" />
        <my-comp v-shortkey.native="['meta', 'enter']" @shortkey="() => console.log('2')" />
        <my-comp v-shortkey.native="['meta', 'enter']" @shortkey="() => console.log('3')" />
    </div>
</template>
```

and I then use the key combination, the console will only display '3', ignoring which component has focus or even if none of them has focus. 

Not sure if that can be addressed at all really, but I thought I'd log that here to bring it to your attention.

**Comment by francois2metz** [comment]
Yup, currently the focused element does not matter. What you expected/wanted it to register all these handlers and only trigger the one that is focused?

**Comment by Brendonald** [comment]
Yea, ideally it would be great for the event to trigger from the focused component. Again, not sure how feasible it is, however if not, I would still expect all three components to have there v-shortkey directive called. At the moment, it seems like a given key combination (say `['meta', 'enter']`) can only be registered once. I haven't tested extensively though, I might be wrong.
