### ISSUE TITLE
Shortcuts fire even though they are listed in the "prevent" array when initialized

### ISSUE THREAD

**Issue by nagarjun** [iFgR/vue-shortkey#42]
I have an `<input type="text" class="form-input" v-shortkey="{up: ['arrowup'], down: ['arrowdown'], tab: ['tab'], esc: ['esc'], enter: ['enter']}" @shortkey="handleShortcut">` input box in my project. It works fine however, it invokes these keyboard shortcuts throughout the app. I understand that this is the standard behavior of vue-shortkey however, it is breaking some functionality of [vue-tags-input](https://www.npmjs.com/package/@johmun/vue-tags-input).

vue-tags-input creates an input box like this: `<input type="text" class="new-tag-input valid">` which allows the user to enter tags and use arrow keys to select suggestions. To avoid the conflict, I am initializing vue-shortkey like this:

`Vue.use(VueShortkey, { prevent: ['input.valid'] });`

While this fixed my issue with vue-tags-input (I am able to use my arrow keys to select tags), it broke my other input above (the one with class="form-input" which actually has the v-shortkey attribute). vue-shortkey has disabled all shortcuts on `input.form-input`. I am using vue-shortkey version 3.1.0. How can I fix this?

**Comment by iFgR** [comment]
Hi!
Can you share the code?
