### ISSUE TITLE
Question: How to add shortcut to Vue Router Link?

### ISSUE THREAD

**Issue by ncjones** [iFgR/vue-shortkey#49]
I'm trying to add a shortcut to a vue router link but I can't figure out what I need to do to get it working:

```vue 
<router-link v-shortkey.once="['ctrl', 'shift', 't']" @shortkey="navigate" to="/items/add">
   Add Item                                                   
</router-link>
```

The "navigate" method referenced in the "shortkey" event handler is never called. What do I need to do to get this to work?

**Comment by francois2metz** [comment]
Hi,

You should use the `native` modifier to catch the event, see https://github.com/iFgR/vue-shortkey#using-on-a-component

**Comment by ncjones** [comment]
@CalebKester sorry after struggling with this issue I gave up on the problem so I don't have a solution to share. Let us know if you found a working solution.

**Comment by CalebKester** [comment]
@ncjones I realized my solution was simple. I wanted to reuse the same route, so i just did this:

```
		<router-link
			v-shortkey.once="['k']"
			v-if="$slots.left"
			:to="left.to"
			:class="[$style.link, $style.linkLeft]"
			title="hotkey: [ k ]"
			@shortkey.native="navigate(left.to)"
		>Back</router-link>```
...
```
	methods: {
		navigate(to) {
			this.$router.push(to);
		},
	},```
