### ISSUE TITLE
v-shortkey.avoid documentation

### ISSUE THREAD

**Issue by hworld** [iFgR/vue-shortkey#5]
The documentation says it's `v-shortkey.void` but it's actually `avoid`. Had to look at the code to figure out what was going on.

**Comment by iFgR** [comment]
You're right.
I change the decoumentation.
Thx!

**Comment by hworld** [comment]
Nice. Still says it here, though: "Preventing a given element from executing the shortcut by adding the v-shortkey.void tag in the body of the element"

**Comment by iFgR** [comment]
Perfect, thanks again!!!
If you can check the spelling or something that might be better written, I would greatly appreciate it.

**Comment by hworld** [comment]
You bet, if I see something I'll be sure to bring it here. The only other thing I don't understand is what the "push" thing does. I looked in the code and it looks like it may be a one-time trigger? Like it deregisters itself after it is triggered?

**Comment by iFgR** [comment]
"Push" calls the function one time until you release the shortcut . When you release the shortcut, it call the same function again like a toggle.

"Once" call a function only one time when the shortcut is activated
