### ISSUE TITLE
ESC + textarea

### ISSUE THREAD

**Issue by jakubsacha** [iFgR/vue-shortkey#51]
Hey, 

Thank you for that lovely plugin. It's very useful! 

My use case is following: 
I open modal when "n" is pressed. Then i focus <v-input> so that user can type in whatever needed. What i'd like to achieve is: when user presses "ESC" key, modal is closed. Since i use: ``Vue.use(ShortKey, { prevent: ['input', 'textarea'] })`` and i'm in the focused input field, obviously shortcut call is prevented. I'm actually not sure how can i make ESC and only ESC work only in the input field. 

Any thoughts on that?

**Comment by iFgR** [comment]
Hi,
Thank you for your appreciation!
It's an interesting situation that doesn't have an apparent solution.

@francois2metz do you see any solution? What do you think about to create an modifier like **.escapeavoid** to escape the "avoided" fields?

**Comment by jakubsacha** [comment]
What i'm thinking about is more generic solution. 

Maybe something like that?:
```javascript
Vue.use(ShortKey, { prevent: [{element: 'input'}, {element: 'textarea', except: ['esc', 'ctrl']}] })
```
and inline version:
```html
<textarea v-shortkey.avoid="except: ['esc', 'ctrl']"></textaea>
```

**Comment by iFgR** [comment]
@jakubsacha good point!

And what if you used the class name to define it? like this:
```javascript
Vue.use('vue-shortkey', { prevent: ['input', 'textarea.textarea-avoided'] })
```
This can already be done now.

Anyway, I'll be thinking about **except** in this case!

**Comment by jakubsacha** [comment]
I'm not sure if i understand fully, but what about following?
```
Vue.use(ShortKey, { prevent: [{element: '.whatever', except: ['esc', 'ctrl']}] })
```

**Comment by EnginMicoogullari** [comment]
Thank you for an awesome plugin, really appritiate your work!

I have a user case where I want to use the tab-key to jump between inputs. I have a data-table with 2 columns and I populate these 2 columns with input-fields via a for-loop. Usually a tab-key jumps to the next input to the right. But I want the key to jump downwards instead of to the side by default. Any idea if I can accomplish this this with vue-shortkey?

Thanks in advance for your time!

**Comment by iFgR** [comment]
@EnginMicoogullari you're welcome!
Try it [https://jsfiddle.net/KingUnnamed/3k2yxw90/25/](https://jsfiddle.net/KingUnnamed/3k2yxw90/25/)

**Comment by iFgR** [comment]
I will link this issue with the #53 and follow along there
