### ISSUE TITLE
How can I prevent hotkeys from firing while writing text in a span?

### ISSUE THREAD

**Issue by michaelschufi** [iFgR/vue-shortkey#52]
Hi

I have the following components:

A "Home" component which looks like this:
```html
<template>
  <div class="home" v-shortkey="['a']" @shortkey="goToAdd()">
    <v-subheader>Active ({{ activeTodos.length }})</v-subheader>
    <TodoList :todos="activeTodos"></TodoList>
    <router-link to="/add">
      <v-btn fab bottom right color="pink" dark fixed>
        <v-icon>add</v-icon>
      </v-btn>
    </router-link>
  </div>
</template>
```
And down in the tree of the shown TodoList another component, which lets me edit the description of a todo:
```html
<template>
  <div class="disablehotkeys">
    <span v-shortkey.avoid contenteditable class="disablehotkeys description subheading" @blur="updateDescription($event)">{{ todo.description }}</span>
  </div>
</template>
```

Now, when the span-tag is focused and I am typing a word with an "a", the shortkey event of the Home component is firing, even though I have disabled v-shortkey on the tag (and the div).

I am initialising vue-shortkey with `Vue.use(VueShortkey, { prevent: ["input", "textarea", ".disablehotkeys"] });`

How can I prevent the event from firing?

**Comment by iFgR** [comment]
Did you already try to insert the tabindex tag into the span?

**Comment by michaelschufi** [comment]
Thanks! That solved the problem. :D
