### ISSUE TITLE
More than two keys doesn't work

### ISSUE THREAD

**Issue by kendallroth** [iFgR/vue-shortkey#57]
I've been testing a few combinations and haven't gotten a keybind with more than 2 keys to work. For example, `ctrl + m` works but `ctrl + shift + m` doesn't. Additionally, `ctrl + alt` works but `ctrl + alt + m` does (although neither does `alt + m`...).

```
<template>
  <div id="app">
    <v-app
      v-shortkey="['ctrl', 'm']"
      @shortkey.native="onToggle()"
    >
      <v-content>
        <router-view/>
      </v-content>
    </v-app>
  </div>
</template>
```

I am using Chrome on a Mac.

**Comment by iFgR** [comment]
It's because the order of the keys matters.
You need to do an array like this:
```javascript
v-shortkey="['shift', 'ctrl', 'm']"
```

I am working to fix this.

**Comment by kendallroth** [comment]
BTW, thanks for the explanation (never acknowledged before)
