### ISSUE TITLE
Does vue-shortkey remove the event listener from the document when vue destroys the element?

### ISSUE THREAD

**Issue by lukechinworth** [iFgR/vue-shortkey#58]
I don't see `removeEventListener` anywhere in the source, so I was curious if the listeners get removed.

**Comment by michaelschufi** [comment]
It adds event listeners on the `document`, which means there is no listener on the element which gets destroyed.
See:
https://github.com/iFgR/vue-shortkey/blob/42fc003a0a333efa86a98a47357f8bfcfa771027/src/index.js#L114

**Comment by iFgR** [comment]
Part of the strategy was don't create listeners for each element or, as I like to say, actions.
We mount a unique listener who will interpret and dispatch the action. It will live on the entire aplication life until it's destroyed.

So, don't be afraid, We don't have many listener

**Comment by lukechinworth** [comment]
Ah, I see. So just one listener. Cool thanks!
