### ISSUE TITLE
Cmd on mac

### ISSUE THREAD

**Issue by JosephSmith127** [iFgR/vue-shortkey#6]
It would be nice to allow the option to use "cmd" instead of "ctrl" when someone is using a mac 😊

**Comment by iFgR** [comment]
Certainly!
My fault, I didn't think of it :(

I'll work on it.

**Comment by hekigan** [comment]
in Sublime text, they use the "super" keyword. it makes the name kind of universal.
That way, it translates to "cmd" for Mac and "windows" equivalent on Windows (don't remember the exact name for the key).

**Comment by iFgR** [comment]
Hi,
I've created a new version with cmd key.
Could you test?

**Comment by enricribas** [comment]
I *think* what the poster was suggesting is the ability to do Ctrl-something on Window/Linux and Cmd-same on Mac. This is pretty standard for many apps like VSCode for example. Cmd-p versus Ctrl-p.
