### ISSUE TITLE
Using without CommonJS or webpack

### ISSUE THREAD

**Issue by shah-newaz** [iFgR/vue-shortkey#60]
Is it possible to use this plugin without webpack/commonJS?
I have a project where Vue JS is being used as standalone. Is there a way to use this plugin in a setup like that ?

e.g.,
```
<script src="/vendor/redprint/vendor/vue/vue.min.js"></script>
<script>
        var app = new Vue({
        .....
        .....
```
Thanks!

**Comment by iFgR** [comment]
Like this:
[https://jsfiddle.net/KingUnnamed/9rxk2ufe/7/](https://jsfiddle.net/KingUnnamed/9rxk2ufe/7/)
