### ISSUE TITLE
Problem with Internet Explorer 11

### ISSUE THREAD

**Issue by Kai9026** [iFgR/vue-shortkey#62]
Hi!,

I just added the vue-shortkey library to my project and I noticed some bugs in Internet Explorer 11. When I opened the developer's web console, I found the following messages:

In Spanish:
- SCRIPT438: El objeto no acepta la propiedad o el método 'find'. 
In English:
- SCRIPT438: The object does not accept the 'find' property or method.
Here an image:
![image](https://user-images.githubusercontent.com/23612650/45033994-83389680-b056-11e8-9550-1cb9642944cb.png)

Am I doing something wrong or is it a bug?
Regards.

**Comment by iFgR** [comment]
Hi!
Unfortunately IE11 doesn't support the .find prototype.

To solve this, you can try to add the polyfill on the root of your javascript project for IE11 support.
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill)

**Comment by Kai9026** [comment]
@iFgR first of all, thanks for your reply!

Before opening this issue, I had already tried to implement the find() and includes() polyfills that were causing this problem.
However, after solving this problem, the line where new Event() appears, fails. I haven't seen that there is a polyfill available for this builder.

Regards.

**Comment by iFgR** [comment]
Are you using babel or another preprocessor?

**Comment by Kai9026** [comment]
Hi @iFgR! Yes, I do. I'm using Babel.

**Comment by sShrek1** [comment]
@Kai9026 any luck with this issue? I have same issue...

**Comment by sShrek1** [comment]
For anyone with same issue, this worked for me: 

1. `npm install --save @babel/polyfill`
2. in **webpack.config.js** add this:
`entry: ["@babel/polyfill", "./app/js"],` **modify so it matchs your path**

https://babeljs.io/docs/en/babel-polyfill

**Comment by Kai9026** [comment]
> For anyone with same issue, this worked for me:
> 
> 1. `npm install --save @babel/polyfill`
> 2. in **webpack.config.js** add this:
>    `entry: ["@babel/polyfill", "./app/js"],` **modify so it matchs your path**
> 
> https://babeljs.io/docs/en/babel-polyfill

Thanks @sShrek1,

I had tried a lot of things ,so far, but I'm going to try this. 
Let's see if I'm lucky. 

Regards.

**Comment by Kai9026** [comment]
Hi @sShrek1,

I've tried your solution but it doesn't work for me 👎. Did you just install @babel/polyfill, or did you add any more dependencies?. I have problems with the 'new Event()' inside index.js of Vue-shortkey.

Regards.

**Comment by sShrek1** [comment]
@Kai9026 Hmm.. I just installed using `npm install --save @babel/polyfill` then in my web.config.js i just modified my entry from `entry: './Scripts/app/main.js'` to `entry: ["@babel/polyfill", './Scripts/app/main.js']`

Can you post just your entry-field from webpack.config.js so I can look at it?

**Comment by Kai9026** [comment]
Yes @sShrek1,

This is my configuration:
...
entry: {
    app: ["@babel/polyfill","./src/main.js"]
  },
...
Regards.

**Comment by sShrek1** [comment]
@Kai9026 hmm.. Well it looks right. 
Can you create an project/copy yours (delete files etc) and push to your git?

**Comment by sShrek1** [comment]
@Kai9026 seems we didnt make it to work. Using CDN actually worked, probably something with how we installed polyfill. 
Even if that works, the Custom event (left: ['ctrl' + 'arrowleft']) doesnt work. IE11 doesnt support ES6 (arrow functions). I will work on workaround and tell you when its done. :)

**Comment by iFgR** [comment]
@Kai9026  Was solved?

**Comment by iFgR** [comment]
@Kai9026 great!
I hope that your solution helps another people.

**Comment by Kai9026** [comment]
@iFgR Thanks for your attention.
I hope the same thing.
