### ISSUE TITLE
backspace key

### ISSUE THREAD

**Issue by JoachimR** [iFgR/vue-shortkey#63]
Hi there!

Thank you very much for this plugin!

I wanted to catch the key event `backspace`. But at least on a Mac the `'del'` shortkey is not triggered when pressing `backspace`. Did I miss something or is it just not included so far? If so, could you maybe add it?

**Comment by thenikso** [comment]
Same here. maybe an `option` in installation phase could cover this and future similar problems

**Comment by iFgR** [comment]
I don't have a Mac computer to do some tests.
I'll run some tests and ask you guys to take a look, could you?

**Comment by JoachimR** [comment]
yeah sure I can test. However I am wondering if backspace is working on Windows? I mean I do not have to press any special meta character for it .. ?

**Comment by thenikso** [comment]
great news that #70 have been merged with backspace support! 

Is there an npm publishing with a new version containing the change in sight?

**Comment by iFgR** [comment]
@thenikso The package is in the latest version with Backspace support!

**Comment by thenikso** [comment]
hmm I have version `3.1.6` from npm and it does not seams to have the backspace bit it in. In fact 3.1.6 seams to have been committed 30607c953a7f34e449e829aecbeb50c39dc62231 before the backspace merge?

**Comment by danielgolden** [comment]
I was going to mention that this wasn't working for me even with the latest version. Thought I was just missing something.
