### ISSUE TITLE
Preventing Google Chrome default shortcuts

### ISSUE THREAD

**Issue by AlexandruMiricioiu** [iFgR/vue-shortkey#71]
It is possible to prevent or override web browser sortcuts (ie Google Chrome) ?
I'm trying to use `v-shortkey="['ctrl', 'tab']"` | | `v-shortkey="['ctrl', 's']"` but chrome shortcut fires.

Thank you.

**Comment by m-bryo** [comment]
I'm having same issues too...
As a temporary fix.. I'm using `alt` instead of `ctrl`, so i have 
`v-shortkey="['alt', 'n']` in place of `v-shortkey="['ctrl', 'n']`

**Comment by sarkiroka** [comment]
Okay, I accept to cannot use "ctrl+tab" but I cannot use "alt-tab" or "shift+tab" or "ctrl+shift+tab" or "anything+tab" :(

**Comment by iFgR** [comment]
I'll check this

**Comment by jwheatp** [comment]
Hey, I managed to do it manually, here an example.

In your template :
```
<button v-shortkey="['meta', 'r']" @shortkey="run">
```

In your methods :
```
run: function(e) {
    if (e.ctrlKey || e.metaKey) {
        var c = e.which || e.keyCode; // get key code
        switch (c) {
            case 83: //block Ctrl+S
                e.preventDefault();     
            case 82: //block Ctrl+R
                e.preventDefault();     
            break;
        }
    }
}
```

Inspired from : https://stackoverflow.com/a/24764878
Keycodes (like 83 and 82 above) can be get from https://keycode.info/.

**Comment by sarkiroka** [comment]
@iFgR, it is very sad

**Comment by iFgR** [comment]
@sarkiroka unfortunately.
I wanted to to catch the Volume button, play and pause but I couldn't.
