### ISSUE TITLE
Please bump NPM version so that the backspace support is included

### ISSUE THREAD

**Issue by dpschen** [iFgR/vue-shortkey#76]
I need the (alredy merged) pull request https://github.com/iFgR/vue-shortkey/pull/70 with support for the backspace key.

In the version 3.1.6 on NPM that pull request is sadly not yet included.
Could you please bump the NPM version of the package?

**Comment by iFgR** [comment]
Oh friend, of course!

**Comment by dpschen** [comment]
Thx
