### ISSUE TITLE
Getting "ReferenceError: document is not defined" error when imported in nuxt app.ts

### ISSUE THREAD

**Issue by madhuadbanker** [iFgR/vue-shortkey#77]
I am using below code in nuxt app.ts file and when compiling i am getting "ReferenceError: document is not defined" error
const Vue = require('Vue');
const ShortKey = require('vue-shortkey');
Vue.use(ShortKey);

Can any one help me in loading this component without errors.

**Comment by madhuadbanker** [comment]
I am using vue application with nuxt. I have added the plugin as mentioned in nuxt documentation in 2 ways . 
1. create pligins/vue-shortkey.js and given path in nuxt.config.js ...i got vue warning failed to resolve directive-shortkey
2. another way..my plugin in node_modules so given in build option of nuxt.config.js as transpile:['vue-shortkey'] but didnt create plugins/vue-shortkey.js...here also same error

another way i tried by give Vue.use(require('vue-shortkey'))in app.ts ..here i got document not found

**Comment by kespaldon** [comment]
It most likely mean that the script is being run serverside. Make sure you have `mode: "client"` added in your `nuxt.config.ts`

```
plugins: [
    { src: "@/plugins/vue-shortkey.js", mode: "client" },
  ],
```
