### ISSUE TITLE
package.json is missing link to GitHub

### ISSUE THREAD

**Issue by dcecile** [iFgR/vue-shortkey#8]
For example, see the npm page for [vue](https://www.npmjs.com/package/vue), which has a link to [github.com/vuejs/vue](https://github.com/vuejs/vue).

I'm not sure, but I'm guessing this is populated by the ["repository"](https://github.com/vuejs/vue/blob/43485fbc5b779e02122c3b7fc64296a2cfee31f6/package.json#L42) field in `package.json`.

**Comment by iFgR** [comment]
Updated, thank you!
