### ISSUE TITLE
Not working with SSR?

### ISSUE THREAD

**Issue by cjblomqvist** [iFgR/vue-shortkey#82]
It seems this doesn't work nicely with SSR. Unfortunately, I don't have time to report a more proper case, or do a PR to fix it, but I thought this is something which should be brought to attention since this limits the usability of the library significantly (if true), which is very sad since this seems to be the most complete keyboard-handling library out there for vue.

**Comment by iFgR** [comment]
Thanks for the report. I didn't make any tests on SSR application.
I'll do some tests...

**Comment by jeremyabraham7** [comment]
@cjblomqvist Are you using NUXT SSR? If so this is how I got things working with Nuxt:

Added vue-shortkey.js to /plugins: 
```import Vue from 'vue'
const ShortKey = require('vue-shortkey')

Vue.use(ShortKey, { prevent: ['input', 'textarea'] })
export default ShortKey```

Load the plugin in nuxt.config.js:
```plugins: [ { src: '@/plugins/vue-shortkey.js', ssr: false }]```

**Comment by cjblomqvist** [comment]
Don't use nuxt, but a more vanilla SSR approach according to the official SSR docs.
