### ISSUE TITLE
How to implement multiple shortcut key?

### ISSUE THREAD

**Issue by nqthiep** [iFgR/vue-shortkey#9]
Hi Fagner Araujo,

Thank you for your useful plugin.
I have a problem and need your help.

I have a button, I want when I press Ctrl + 1, the program will execute theAction1 () and when I press Ctrl + 2, the program will execute theAction2 ().

<button 
	v-shortkey="[['ctrl', '1'], ['ctrl', '2']]" 
	@shortkey="[theAction1(), theAction2()]">Open
</button>

Currently I have no way to solve this problem.
Can you give me some suggestions or how to handle that problem?

Thank you again.

**Comment by iFgR** [comment]
Hi, Nguyen Quang Thiep! How are you?
Ok, the plugin doesn't support multiple shortcuts. I confess I did not even think of this possibility when I created it.

Think of the shortkey as a button. One button can not do 2 different actions. It only performs click action.

Anyway, the shortkey can be attached to anything so, you can create a div with shortkey pointing to an "action2" for example.

Take a look at this:
```html
<div class="button-container" v-shortkey="['ctrl', '1']" @shortkey="theAction1">
   <button class="button-container--my-button" v-shortkey="['ctrl', '2']" @shortkey="theAction2" />
</div>
```
What you think about it?

**Comment by nqthiep** [comment]
Hi Fagner Araujo,

Thank you for your quick support
And sorry for my late response.

> Think of the shortcut as a button. One button can not do 2 different actions. It only performs click action.
You're right in the case that the button only has one function.
But in cases where that node has many functions then that is no longer the case.

> Anyway, the shortcut can be attached to anything so, you can tạo a div with the shortcut pointing to an "action2" for example.
I agree with you that this way will work well.
But in cases where I need to do a lot of shortcuts then by doing this we will have to add more div tags, I think this is not good.

Do you have any other ideas?

**Comment by nickforddesign** [comment]
Yeah this is unfortunate, I agree with @nqthiep

**Comment by Saunved** [comment]
I figured one way to do it is for using multiple shortcuts is to **define invisible buttons on the UI** and attach `v-shortkey` and `@shortkey` to them as usual. The user won't see the buttons, but they'll be able to perform the shortcuts regardless.
