### ISSUE TITLE
Same shortkey on differente actions into the same component

### ISSUE THREAD

**Issue by calebeaires** [iFgR/vue-shortkey#99]
Suppose we are into a page that has this ESC shortkey. The main objective is: get out of the page; but into the same page we have an MODAL/Dialog component that we want use  the same ESC shortkey to close it. 

I have tried to use vue-shortkey in this way, but when I use the multiple actions with the same shortkey into the same component, all of then are executed. 

Is there some way to execute sequencially the same shortkey?

**Comment by iFgR** [comment]
Vue-Shortkey doesn't have _onFocus_ listener, it is ery expensive but, you have some ways to do it.
You can do a _onFocus_ senor by your self or, for me the best approach, use one short-key and a flag to route what the method will be dispatched.

**Comment by calebeaires** [comment]
Great, thanks!
